Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,15 +3,19 @@ run-name: "Project Build #${{ github.run_number }}"
 on:
   push:
     branches:
+      - dev
       - main
 
 concurrency:
-  group: ${{ github.workflow }}
+  group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true
 
 env:
   RELEASE_TYPE: "release"
   MINECRAFT_VERSION: "1.20.1"
+  RELEASE_ON_GITHUB: "true"
+  RELEASE_ON_CURSEFORGE: "true"
+  RELEASE_ON_MODRINTH: "false"
 
 jobs:    
   info:
@@ -23,8 +27,6 @@ jobs:
       project_full_name: ${{ steps.project_name.outputs.value }}-${{ steps.project_version.outputs.value }}
       changelog: ${{ steps.changelog.outputs.description }}
       diff: ${{ steps.read_diff.outputs.diff }}
-      release_type: ${{ env.RELEASE_TYPE }}
-      minecraft_version: ${{ env.MINECRAFT_VERSION }}
       exists: ${{ steps.check_tag.outputs.exists }}
     
     steps:
@@ -327,6 +329,7 @@ jobs:
     name: 🚀 Release to GitHub
     needs: [info, build-modpack, build-server, build-multimc]
     runs-on: ubuntu-latest
+    if: env.RELEASE_ON_GITHUB != 'true' && github.branch == 'main'
     outputs:
       url: ${{ steps.release.outputs.url }}
 
@@ -338,6 +341,24 @@ jobs:
         uses: actions/download-artifact@v4.2.1
         with:
           merge-multiple: true
+
+      - name: 🔍 Check if artifact exist
+        id: check_artifact
+        shell: bash
+        run: |
+          if [ ! -f ${{ needs.info.outputs.project_full_name }}-curseforge.zip ]; then
+            echo '::error::No value found for artifact `curseforge.zip`.' && exit 1
+          fi
+          if [ ! -f ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack ]; then
+            echo '::error::No value found for artifact `modrinth.mrpack`.' && exit 1
+          fi
+          if [ ! -f ${{ needs.info.outputs.project_full_name }}-serverpack.zip ]; then
+            echo '::error::No value found for artifact `serverpack.zip`.' && exit 1
+          fi
+          if [ ! -f ${{ needs.info.outputs.project_full_name }}-multimc.zip ]; then
+            echo '::error::No value found for artifact `multimc.zip`.' && exit 1
+          fi
+          echo "✔️ All artifacts found"
 
       - name: 🚫 Сlose fixed in dev
         uses: Xikaro/close-issues-based-on-label@master
@@ -369,7 +390,7 @@ jobs:
             ${{ needs.info.outputs.project_full_name }}-curseforge.zip
             ${{ needs.info.outputs.project_full_name }}-serverpack.zip
             ${{ needs.info.outputs.project_full_name }}-multimc.zip
-          prerelease: ${{ needs.info.outputs.release_type != 'release' }}
+          prerelease: ${{ env.RELEASE_TYPE != 'release' }}
           generate_release_notes: true
           token: ${{ secrets.GITHUB_TOKEN }}
 
@@ -377,6 +398,7 @@ jobs:
     name: 🚀 Release to CurseForge
     needs: [info, build-modpack, build-server, release-github]
     runs-on: ubuntu-latest
+    if: env.RELEASE_ON_CURSEFORGE != 'true' && github.branch == 'main'
     outputs:
       id: ${{ steps.release.outputs.id }}
 
@@ -388,15 +410,22 @@ jobs:
             echo '::error::No value found for secret key `CURSEFORGE_TOKEN`. See https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
           fi  
 
-      - name: 📦 Download artifact curseforge
+      - name: 📦 Download artifact
         uses: actions/download-artifact@v4.2.1
         with:
-          name: ${{ needs.info.outputs.project_full_name }}-curseforge
+          merge-multiple: true
 
-      - name: 📦 Download artifact server
-        uses: actions/download-artifact@v4.2.1
-        with:
-          name: ${{ needs.info.outputs.project_full_name }}-serverpack
+      - name: 🔍 Check if artifact exist
+        id: check_artifact
+        shell: bash
+        run: |
+          if [ ! -f ${{ needs.info.outputs.project_full_name }}-curseforge.zip ]; then
+            echo '::error::No value found for artifact `curseforge.zip`.' && exit 1
+          fi
+          if [ ! -f ${{ needs.info.outputs.project_full_name }}-serverpack.zip ]; then
+            echo '::error::No value found for artifact `serverpack.zip`.' && exit 1
+          fi
+          echo "✔️ All artifacts found"
 
       - name: 🚀 Upload Curseforge
         id: release
@@ -412,46 +441,56 @@ jobs:
             ${{ needs.info.outputs.changelog }}
             ${{ needs.info.outputs.diff }}
           changelog-format: markdown
-          game-version: ${{ needs.info.outputs.minecraft_version }}
-          release-type: ${{ needs.info.outputs.release_type }}
+          game-version: ${{ env.MINECRAFT_VERSION }}
+          release-type: ${{ env.RELEASE_TYPE }}
 
-  # release-modrinth:
-  #     name: 🚀 Release to Modrinth
-  #     needs: [info, build-modpack, build-server, release-github]
-  #     runs-on: ubuntu-latest
+  release-modrinth:
+      name: 🚀 Release to Modrinth
+      needs: [info, build-modpack, build-server, release-github]
+      runs-on: ubuntu-latest
+      if: env.RELEASE_ON_MODRINTH != 'true' && github.branch == 'main'
+      outputs:
+        id: ${{ steps.release.outputs.id }}
 
-  #     steps:
-  #       - name: 🔒 Check if MODRINTH_API_TOKEN exist
-  #         shell: bash
-  #         run: |
-  #           if [ "${{ secrets.MODRINTH_TOKEN }}" == '' ]; then
-  #             echo '::error::No value found for secret key `MODRINTH_TOKEN`. See https://docs.github.com/en/  actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
-  #           fi  
+      steps:
+        - name: 🔒 Check if MODRINTH_API_TOKEN exist
+          shell: bash
+          run: |
+            if [ "${{ secrets.MODRINTH_TOKEN }}" == '' ]; then
+              echo '::error::No value found for secret key `MODRINTH_TOKEN`. See https://docs.github.com/en/  actionssecurity-guides/  encrypted-secrets#creating-encrypted-secrets-for-a-repository' && exit 1
+            fi  
     
-  #       - name: 📦 Download artifact modrinth
-  #         uses: actions/download-artifact@v4.2.1
-  #         with:
-  #           name: ${{ needs.info.outputs.project_full_name }}-modrinth
+        - name: 📦 Download artifact
+          uses: actions/download-artifact@v4.2.1
+          with:
+            merge-multiple: true
+
+        - name: 🔍 Check if artifact exist
+          id: check_artifact
+          shell: bash
+          run: |
+            if [ ! -f ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack ]; then
+              echo '::error::No value found for artifact `modrinth.mrpack`.' && exit 1
+            fi
+            if [ ! -f ${{ needs.info.outputs.project_full_name }}-serverpack.zip ]; then
+              echo '::error::No value found for artifact `serverpack.zip`.' && exit 1
+            fi
+            echo "✔️ All artifacts found"
     
-  #       - name: 📦 Download artifact server
-  #         uses: actions/download-artifact@v4.2.1
-  #         with:
-  #           name: ${{ needs.info.outputs.project_full_name }}-serverpack
-    
-  #       - name: 🚀 Upload Modrinth
-  #         id: release
-  #         uses: Xikaro/upload-curseforge-modpack-action@1.1.1
-  #         with:
-  #           api-token: ${{ secrets.MODRINTH_TOKEN }}
-  #           project-id: ${{ vars.MODRINTH_ID }}
-  #           modpack-path: ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
-  #           modpack-server-path: ${{ needs.info.outputs.project_full_name }}-serverpack.zip
-  #           changelog: ${{ needs.info.outputs.changelog }}
-  #           changelog-format: markdown
-  #           game-version: ${{ needs.info.outputs.minecraft_version }}
-  #           display-name: ${{ needs.info.outputs.project_full_name }}
-  #           server-display-name: ${{ needs.info.outputs.project_full_name }}-serverpack
-  #           release-type: ${{ needs.info.outputs.release_type }}
+        - name: 🚀 Upload Modrinth
+          id: release
+          uses: Xikaro/upload-curseforge-modpack-action@1.1.1
+          with:
+            api-token: ${{ secrets.MODRINTH_TOKEN }}
+            project-id: ${{ vars.MODRINTH_ID }}
+            modpack-path: ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack
+            modpack-server-path: ${{ needs.info.outputs.project_full_name }}-serverpack.zip
+            changelog: ${{ needs.info.outputs.changelog }}
+            changelog-format: markdown
+            game-version: ${{ env.MINECRAFT_VERSION }}
+            display-name: ${{ needs.info.outputs.project_full_name }}
+            server-display-name: ${{ needs.info.outputs.project_full_name }}-serverpack
+            release-type: ${{ env.RELEASE_TYPE }}
 
 
   discord-message:
@@ -475,8 +514,8 @@ jobs:
           content_links_no_embed: .+
           content: |
             **Release**: `${{ needs.info.outputs.project_version }}`
-            **Release Type**: `${{ needs.info.outputs.release_type }}`
-            **Game Version**: `${{ needs.info.outputs.minecraft_version }}`
+            **Release Type**: `${{ env.RELEASE_TYPE }}`
+            **Game Version**: `${{ env.MINECRAFT_VERSION }}`
 
             [CurseForge](https://www.curseforge.com/minecraft/modpacks/terrafirmagreg-modern/files/${{ needs.release-curseforge.outputs.id }}) • [GitHub](${{ needs.release-github.outputs.url }}) • [Issues](https://github.com/${{ github.repository }}/issues)
             ```markdown
