Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -376,9 +376,9 @@ jobs:
           if [ ! -f ${{ needs.info.outputs.project_full_name }}-curseforge.zip ]; then
             echo '::error::No value found for artifact `curseforge.zip`.' && exit 1
           fi
-          if [ ! -f ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack ]; then
-            echo '::error::No value found for artifact `modrinth.mrpack`.' && exit 1
-          fi
+          # if [ ! -f ${{ needs.info.outputs.project_full_name }}-modrinth.mrpack ]; then
+          #   echo '::error::No value found for artifact `modrinth.mrpack`.' && exit 1
+          # fi
           if [ ! -f ${{ needs.info.outputs.project_full_name }}-serverpack.zip ]; then
             echo '::error::No value found for artifact `serverpack.zip`.' && exit 1
           fi
